application: redditwatch
version: 1
runtime: python
api_version: 1

handlers:
- url: /ping
  script: cron/ping.py
  login: admin

- url: /preprocess/\d+
  script: cron/preprocess.py
  login: admin

- url: .*
  script: main.py

